-- TẠO CƠ SỞ DỮ LIỆU  QUẢN LÝ BỆNH VIỆN 
CREATE DATABASE QLBV 
GO

-- DÙNG CƠ SỞ DỮ LIỆU QUẢN LÝ BỆNH VIỆN 
USE QLBV 
GO 

-- XOÁ CƠ SỞ DỮ LIỆU QUẢN LÝ BỆNH VIỆN 
--DROP DATABASE QLBV 

-- TẠO BẢNG BỆNH NHÂN 
CREATE TABLE BENHNHAN (
    MABN CHAR(20) PRIMARY KEY NOT NULL,HOBN NVARCHAR(30) NOT NULL, TENBN NVARCHAR(30) NOT NULL, SODTH VARCHAR(11), 
	DIACHI NVARCHAR(50), NGAYSINH DATE, PHAI NVARCHAR(10), MABHYT CHAR(15)
)
GO 
-- TẠO BẢNG NHÂN VIÊN 
CREATE TABLE NHANVIEN (
    MANV CHAR(20) PRIMARY KEY NOT NULL, HONV NVARCHAR(30) NOT NULL,  TENNV NVARCHAR(30) NOT NULL, DIACHI NVARCHAR(50), 
    NGAYSINH DATE, PHAI NVARCHAR(10), CHUCVU NVARCHAR(20), VAITRO NVARCHAR(255) NOT NULL, NGAYLV DATE, MAKHOA CHAR (20) NOT NULL

)

GO 
-- TẠO BẢNG KHOA 
CREATE TABLE KHOA (
    MAK CHAR(20) PRIMARY KEY NOT NULL, TENK NVARCHAR(30) NOT NULL, MATRUONGKHOA CHAR(20),
    FOREIGN KEY (MATRUONGKHOA) REFERENCES NHANVIEN(MANV)
	ON DELETE SET NULL
    ON UPDATE CASCADE
)
GO 

-- TẠO BẢNG THUỐC 
CREATE TABLE THUOC (
    MATHUOC CHAR(13) PRIMARY KEY NOT NULL,  TENTHUOC NVARCHAR(100) NOT NULL, GIA MONEY
)
GO 
-- TẠO BẢNG THUỐC 
CREATE TABLE HOADON (
    MAHD CHAR(20) PRIMARY KEY NOT NULL,  MABN CHAR(20) NOT NULL, NGAYLAP DATE, THANHTIEN MONEY,
    FOREIGN KEY (MABN) REFERENCES BENHNHAN(MABN)
	ON DELETE CASCADE 
	ON UPDATE CASCADE 
)
GO 
-- TẠO BẢNG CHI TIẾT HOÁ ĐƠN 
CREATE TABLE CHITIET_HOADON (
    MAHD CHAR(20) NOT NULL,  MAL CHAR(20) NOT NULL,  TENL NVARCHAR(100) NOT NULL, 
    SL INT, THANHTIEN MONEY
    PRIMARY KEY (MAHD, MAL,TENL),
    FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD)    
	ON DELETE CASCADE 
	ON UPDATE CASCADE 

)
GO 
-- TẠO BẢNG DỊCH VỤ 
CREATE TABLE DICHVU (
    MADV CHAR(20) PRIMARY KEY NOT NULL, TENDV NVARCHAR(100) NOT NULL, GIA MONEY
)
GO 

-- TẠO BẢNG BỆNH ÁN 
CREATE TABLE BENHAN (
    MABA CHAR(20) PRIMARY KEY NOT NULL, MABN CHAR(20), NGAYNHAPVIEN DATE, 
    NGAYXUATVIEN DATE, KETQUA NVARCHAR(50),
    FOREIGN KEY (MABN) REFERENCES BENHNHAN(MABN)    
	    ON DELETE CASCADE
        ON UPDATE CASCADE
)
GO 
-- TẠO BẢNG PHÒNG ĐIỀU TRỊ 
CREATE TABLE PHONGDIEUTRI (
    MAPDT CHAR(20) PRIMARY KEY NOT NULL, LOAIPHONG NVARCHAR(30), MABS CHAR(20), MAKHOA CHAR(20) NOT NULL ,
    FOREIGN KEY (MABS) REFERENCES NHANVIEN(MANV)
	 ON DELETE SET NULL
     ON UPDATE CASCADE,
	 FOREIGN KEY (MAKHOA) REFERENCES KHOA (MAK)
	 
)
GO 
-- TẠO BẢNG PHÒNG KHÁM 
CREATE TABLE PHONGKHAM (
    MAPK CHAR(20) PRIMARY KEY NOT NULL, MAK CHAR(20) NOT NULL, 
    MABS CHAR(20), LOAIPK NVARCHAR(100) NOT NULL,
    FOREIGN KEY (MAK) REFERENCES KHOA(MAK) 
	    ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (MABS) REFERENCES NHANVIEN(MANV)
	  
)
GO 
--- TẠO BẢNG MỐI LIÊN KẾT N-N


-- TẠO BẢNG BỆNH NHÂN VỚI PHÒNG KHÁM 
CREATE TABLE BENHNHAN_PHONGKHAM (
    MABN CHAR(20) NOT NULL, MAPK CHAR(20) NOT NULL, NGAYKHAM DATE NOT NULL, 
    PRIMARY KEY (MABN, MAPK), 
    FOREIGN KEY (MABN) REFERENCES BENHNHAN(MABN)
	    ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (MAPK) REFERENCES PHONGKHAM(MAPK)
	    ON DELETE CASCADE
        ON UPDATE CASCADE
)
GO 
-- TẠO BẢNG BỆNH NHÂN VỚI PHÒNG ĐIỀU TRỊ 
CREATE TABLE BENHNHAN_PHONGDIEUTRI (
    MABN CHAR(20) NOT NULL, PHGDT CHAR(20) NOT NULL, NGAYNHAPVIEN DATE NOT NULL,  NGAYXUATVIEN DATE 
    PRIMARY KEY (MABN, PHGDT), 
    FOREIGN KEY (MABN) REFERENCES BENHNHAN(MABN)
	    ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (PHGDT) REFERENCES PHONGDIEUTRI(MAPDT)
	    ON DELETE CASCADE
        ON UPDATE CASCADE
)
GO 
-- TẠO BẢNG MUA_THUOC
CREATE TABLE MUA_THUOC (
     MATHUOC CHAR(13)  NOT NULL,MABN CHAR (20)NOT NULL , SL INT NOT NULL,MABS CHAR (20),
	 PRIMARY KEY (MATHUOC,MABN),
	 FOREIGN KEY (MATHUOC) REFERENCES THUOC (MATHUOC)
	 ON DELETE CASCADE 
	 ON UPDATE CASCADE ,
	 FOREIGN KEY(MABN) REFERENCES BENHNHAN(MABN)
	 ON DELETE CASCADE 
	 ON UPDATE CASCADE ,
	 FOREIGN KEY (MABS) REFERENCES NHANVIEN (MANV)
	 ON DELETE CASCADE 
	 ON UPDATE CASCADE 
 )
GO 
-- TẠO BẢNG SUDUNG_DICHVU
CREATE TABLE SUDUNG_DICHVU(
     MADV CHAR(20) NOT NULL,MABN CHAR (20)NOT NULL , TGIAN DATE, SL INT,
	 PRIMARY KEY (MADV,MABN),
	 FOREIGN KEY (MADV) REFERENCES DICHVU (MADV)
	 ON DELETE CASCADE 
	 ON UPDATE CASCADE, 
	 FOREIGN KEY (MABN) REFERENCES BENHNHAN(MABN)
	 ON DELETE CASCADE 
	 ON UPDATE CASCADE 
)
GO 
-- TẠO KHOÁ NGOẠI 
ALTER TABLE NHANVIEN 
ADD CONSTRAINT FK_NV_K FOREIGN KEY (MAKHOA)
REFERENCES KHOA (MAK)
GO
-- RÀNG BUỘC DUY NHẤT
ALTER TABLE KHOA 
ADD CONSTRAINT UN_TENK UNIQUE (TENK)
GO

ALTER TABLE THUOC 
ADD CONSTRAINT UN_TENT UNIQUE (TENTHUOC)
GO
-- RÀNG BUỘC MIỀN GIÁ TRỊ 
ALTER TABLE NHANVIEN 
ADD CONSTRAINT CK_PHAI CHECK (PHAI=N'NAM' OR PHAI = N'NỮ')
GO

ALTER TABLE NHANVIEN 
ADD CONSTRAINT CK_TUOI CHECK ((YEAR(GETDATE())- YEAR(NGAYSINH)) >=18 )
GO

ALTER TABLE BENHNHAN
ADD CONSTRAINT CK_PBN CHECK (PHAI=N'NAM' OR PHAI = N'NỮ')
GO

ALTER TABLE MUA_THUOC
ADD CONSTRAINT CK_SL CHECK (SL>=1)
GO 

ALTER TABLE THUOC 
ADD CONSTRAINT CK_GIA CHECK (GIA>=0)
GO 

ALTER TABLE HOADON 
ADD CONSTRAINT CK_TT CHECK (THANHTIEN >=0)
GO

ALTER TABLE CHITIET_HOADON 
ADD CONSTRAINT CK_ML CHECK (MAL LIKE 'DV%' OR MAL LIKE 'TH%')
GO 

ALTER TABLE NHANVIEN 
ADD CONSTRAINT CK_MANV CHECK (MANV LIKE  'BS%' OR MANV LIKE 'NV%' OR MANV LIKE 'TK%')
GO
-- RÀNG BUỘC MẠC ĐỊNH 
ALTER TABLE THUOC 
ADD CONSTRAINT DF_GIA DEFAULT 0.0 FOR GIA 
GO 

ALTER TABLE HOADON 
ADD CONSTRAINT DF_TT DEFAULT 0.0 FOR THANHTIEN 
GO
 
ALTER TABLE CHITIET_HOADON 
ADD CONSTRAINT DF_CTHD_TT DEFAULT 0.0 FOR THANHTIEN 
GO 