

-- XUẤT DANH SÁCH BỆNH ÁN 
CREATE PROC SP_XUATBENHAN 
AS
SELECT * FROM BENHAN
GO 
EXEC SP_XUATBENHAN
GO 

-- XUẤT DANH SÁCH BỆNH NHÂN
CREATE PROC SP_XUATBENHNHAN
AS
SELECT * FROM BENHNHAN 
GO 
EXEC SP_XUATBENHNHAN
GO 



-- XUẤT DANH SÁCH DỊCH VỤ 
CREATE PROC SP_XUATDICHVU 
AS
SELECT * FROM DICHVU 
GO 
EXEC SP_XUATDICHVU 
GO 


-- XUẤT DANH SÁCH HOÁ ĐƠN
CREATE PROC SP_XUATHOADON 
AS
SELECT * FROM HOADON 
GO 
EXEC SP_XUATHOADON
GO 

-- XUẤT DANH SÁCH  CHI TIẾT HOÁ ĐƠN
CREATE PROC SP_XUATCHITIET_HOADON 
AS
SELECT * FROM CHITIET_HOADON 
GO 
EXEC SP_XUATCHITIET_HOADON
GO 


-- XUẤT DANH SÁCH KHOA
CREATE PROC SP_XUATKHOA
AS
SELECT * FROM KHOA 
GO 
EXEC SP_XUATKHOA
GO 

-- XUẤT DANH SÁCH MUA THUỐC
CREATE PROC SP_XUATMUATHUOC
AS
SELECT * FROM MUA_THUOC 
GO 
EXEC SP_XUATMUATHUOC
GO 

-- XUẤT DANH SÁCH NHÂN VIÊN 
CREATE PROC SP_XUATNHANVIEN
AS
SELECT * FROM NHANVIEN
GO 
EXEC SP_XUATNHANVIEN
GO 

-- XUẤT DANH SÁCH PHONG ĐIỀU TRỊ 
CREATE PROC SP_XUATPHONGDIEUTRI
AS
SELECT * FROM PHONGDIEUTRI 
GO 
EXEC SP_XUATPHONGDIEUTRI
GO 

-- XUẤT DANH SÁCH PHÒNG KHÁM 
CREATE PROC SP_XUATPHONGKHAM
AS
SELECT * FROM PHONGKHAM 
GO 
EXEC SP_XUATPHONGKHAM
GO 

-- XUẤT DANH SÁCH BỆNH NHÂN - PHÒNG KHÁM 
CREATE PROC SP_XUATBENHNHAN_PHONGKHAM
AS
SELECT * FROM BENHNHAN_PHONGKHAM
GO 
EXEC SP_XUATBENHNHAN_PHONGKHAM
GO 
-- XUẤT DANH SÁCH BỆNH NHÂN - PHÒNG ĐIỀU TRỊ  
CREATE PROC SP_XUATBENHNHAN_PHONGDIEUTRI
AS
SELECT * FROM BENHNHAN_PHONGDIEUTRI
GO 
EXEC SP_XUATBENHNHAN_PHONGDIEUTRI
GO 

-- XUẤT DANH SÁCH SỬ DỤNG DỊCH VỤ 
CREATE PROC SP_XUATSUDUNG_DICHVU
AS
SELECT * FROM SUDUNG_DICHVU 
GO 
EXEC SP_XUATSUDUNG_DICHVU
GO 

-- XUẤT DANH SÁCH THUỐC 
CREATE PROC SP_XUATTHUOC
AS
SELECT * FROM THUOC 
GO 
EXEC SP_XUATTHUOC
GO 
-- xuát mã hoá đơn cho combobox 
CREATE PROC SP_LAYMAHD 
AS
SELECT DISTINCT HOADON.MAHD  FROM HOADON 
GO 
EXEC SP_LAYMAHD
GO 

-- LẤY TÊN CỦA THUỐC 
CREATE PROC SP_LAYTENTHUOC (@MATHUOC CHAR(20))
AS 
SELECT THUOC.TENTHUOC FROM THUOC WHERE MATHUOC = @MATHUOC
GO 

CREATE PROC SP_LAYTENDV (@MADV CHAR(20))
AS 
SELECT TENDV FROM DICHVU WHERE MADV = @MADV 
GO 
-- LẤY THÔNG TIN MUA THUỐC BẰNG MÃ NGƯỜI 
CREATE PROC SP_LAY_MUATHUOC_BANGMA(@MAHD CHAR(20))
AS
SELECT MUA_THUOC.MATHUOC , MUA_THUOC.MABN, MUA_THUOC.SL ,THUOC.GIA, MUA_THUOC.MABS AS N'MÃ BÁC SĨ PHÊ DUYỆT' 
FROM MUA_THUOC ,THUOC,HOADON  
WHERE HOADON.MAHD = @MAHD  AND MUA_THUOC.MABN = HOADON.MABN AND MUA_THUOC.MATHUOC = THUOC.MATHUOC
GO 
--EXEC SP_LAY_MUATHUOC_BANGMA 'HD0001'
--GO 

-- LẤY THÔNG SỬ DỤNG DỊCH VỤ BẰNG MÃ 
CREATE PROC SP_LAY_SDDV_BANGMA(@MAHD CHAR(20))
AS
SELECT SUDUNG_DICHVU.MADV , SUDUNG_DICHVU.MABN,SUDUNG_DICHVU.TGIAN AS N'THỜI GIAN',SUDUNG_DICHVU.SL,DICHVU.GIA
FROM SUDUNG_DICHVU , HOADON, DICHVU 
WHERE HOADON.MAHD = @MAHD  AND SUDUNG_DICHVU.MABN = HOADON.MABN AND SUDUNG_DICHVU.MADV = DICHVU.MADV
GO 