-- Tạo các stored procedures 


--EXEC SP_TIMBACSI_BANGTEN 'NGÂN'
go 
 -- TÌM BỆNH ÁN BẰNG TÊN BỆNH NHÂN 
 CREATE PROC SP_TIMBENHAN_BANGTENBN(@TEN NVARCHAR(30))
 AS
 SELECT BENHAN.MABA, BENHAN.MABN , BENHAN.KETQUA FROM BENHAN , BENHNHAN WHERE BENHAN.MABN = BENHNHAN.MABN AND (TENBN LIKE N'%'+@TEN+'%'OR  BENHNHAN.TENBN = @TEN)
 GO 

 --EXEC SP_TIMBENHAN_BANGTENBN 'THUỶ'
go 
-- tìm bệnh nhân bằng tên 
 CREATE PROC SP_TIMBENHNHAN_BANGTEN(@TEN NVARCHAR(30))
 AS
 SELECT *FROM  BENHNHAN WHERE (TENBN LIKE N'%'+@TEN+'%'OR  BENHNHAN.TENBN = @TEN)
 GO 

 --EXEC SP_TIMBENHNHAN_BANGTEN'TÙNG'
 GO 

--EXEC SP_TIMBHYT_BANGTENBN 'TÙNG'
 GO 

 -- TÌM DỊCH VỤ BẰNG TÊN 
 CREATE PROC SP_TIMDICHVU_BANGTEN(@TEN NVARCHAR(30))
 AS
 SELECT *FROM  DICHVU WHERE( DICHVU.TENDV LIKE N'%'+@TEN+'%' OR  TENDV =  @TEN)
 GO 

 --EXEC SP_TIMDICHVU_BANGTEN 'TH'
 GO 



 -- tìm hoá đơn bằng tên bệnh nhân 
 CREATE PROC SP_TIMHOADON_BANGTENBN(@TEN NVARCHAR(30))
 AS
 SELECT HOADON.MAHD , HOADON.MABN ,HOADON.NGAYLAP,HOADON.THANHTIEN FROM HOADON , BENHNHAN WHERE HOADON.MABN = BENHNHAN.MABN AND (BENHNHAN.TENBN LIKE N'%'+@TEN+'%' OR  BENHNHAN.TENBN =  @TEN)
 GO 

-- EXEC SP_TIMHOADON_BANGTENBN'TÙNG'
 GO 
 

 -- TÌM KIẾM KHOA BẰNG TÊN KHOA 
  CREATE PROC SP_TIMKHOA_BANGTEN(@TEN NVARCHAR(30))
 AS
 SELECT * 
 FROM KHOA 
 WHERE (TENK LIKE N'%'+@TEN+'%' OR  TENK =  @TEN) 
 GO 
 --EXEC SP_TIMKHOA_BANGTEN N'KH'
 GO 




 -- TÌM KIẾM MUA THUỐC BẰNG TÊN THUỐC  
  CREATE PROC SP_TIMMUA_THUOC_BANGTENTHUOC(@TEN NVARCHAR(30))
 AS
 SELECT MUA_THUOC.MATHUOC , MUA_THUOC.MABN , MUA_THUOC.SL
 FROM MUA_THUOC, THUOC
 WHERE  MUA_THUOC.MATHUOC = THUOC.MATHUOC AND ( THUOC.TENTHUOC LIKE N'%'+@TEN+'%' OR  THUOC.TENTHUOC = @TEN)
 GO 
 --EXEC SP_TIMMUA_THUOC_BANGTENTHUOC N'Thuốc Tocemux điều trị tiêu chất nhầy, bệnh lý hô hấp có đờm'
 GO 
   CREATE PROC SP_TIMNHANVIEN_BANGTEN(@TEN NVARCHAR(30))
 AS
 SELECT *
 FROM NHANVIEN
 WHERE ( TENNV LIKE N'%'+@TEN+'%' OR  TENNV = @TEN)
 GO 
 --EXEC SP_TIMNHANVIEN_BANGTEN N'Trung'
 GO 
 -- TÌM KIẾM PHÒNG ĐIỀU TRỊ BẰNG LOẠI PHÒNG 

 CREATE PROC SP_TIMPHONGDIEUTRI_BANGLOAIPHG(@TEN NVARCHAR(30))
 AS
 SELECT *
 FROM PHONGDIEUTRI
 WHERE ( LOAIPHONG LIKE N'%'+@TEN+'%' OR  LOAIPHONG = @TEN)
 GO 
 --EXEC SP_TIMPHONGDIEUTRI_BANGLOAIPHG N'ĐÔI'
 GO 
 -- TÌM KIẾM PHÒNG KHÁM BẰNG LOẠI PHÒNG KHÁM PHÒNG KHÁM 
 CREATE PROC SP_TIMPHONGKHAM_BANGTENKHOA(@TEN NVARCHAR(30))
 AS
 SELECT *
 FROM PHONGKHAM 
 WHERE ( LOAIPK LIKE N'%'+@TEN+'%' OR LOAIPK  = @TEN)
 GO 
 --EXEC SP_TIMPHONGKHAM_BANGTENKHOA N'KHOA NỘI'
 GO

 --TÌM KIẾM PHÒNG KHÁM _ BỆNH NHÂN BẰNG TÊN BỆNH NHÂN 
  CREATE PROC SP_TIMPKHAM_BENHNHAN_BANGTENBN(@TEN NVARCHAR(30))
 AS
 SELECT *
 FROM BENHNHAN_PHONGKHAM ,BENHNHAN
 WHERE BENHNHAN.MABN = BENHNHAN_PHONGKHAM.MABN AND ( BENHNHAN.TENBN LIKE N'%'+@TEN+'%' OR BENHNHAN.TENBN  = @TEN)
 GO 
 --EXEC SP_TIMPKHAM_BENHNHAN_BANGTENBN N'TÙNG'
 GO 

-- TÌM KIẾM SỬ DỤNG DỊCH VỤ BẰNG TÊN BỆNH NHÂN 
  CREATE PROC SP_TIMSUDUNG_DICHVU_BANGTENBN(@TEN NVARCHAR(30))
 AS
 SELECT SUDUNG_DICHVU.MADV, SUDUNG_DICHVU.MABN , SUDUNG_DICHVU.TGIAN , SUDUNG_DICHVU.SL
 FROM SUDUNG_DICHVU , BENHNHAN
 WHERE SUDUNG_DICHVU.MABN = BENHNHAN.MABN AND ( BENHNHAN.TENBN LIKE N'%'+@TEN+'%' OR BENHNHAN.TENBN  = @TEN)
 GO 
 --EXEC SP_TIMSUDUNG_DICHVU_BANGTENBN N'TÙNG'
 GO 
 -- TÌM KIẾM THỐC BẴNG TÊN THUỐC 
   CREATE PROC SP_TIMTHUOC_BANGTEN(@TEN NVARCHAR(30))
 AS
 SELECT *
 FROM THUOC
 WHERE ( TENTHUOC LIKE N'%'+@TEN+'%' OR TENTHUOC  = @TEN)
 GO 
 --EXEC SP_TIMTHUOC_BANGTEN N'Thuốc nhỏ mắt'
 GO
 CREATE PROC SP_TIMKIEM_HOADONCHITIET_BANGTENBN(@TEN NVARCHAR(30))
 AS 
 SELECT  CHITIET_HOADON.MAHD,CONCAT(BENHNHAN.HOBN,' ',BENHNHAN.TENBN) , CHITIET_HOADON.MAL,CHITIET_HOADON.TENL,CHITIET_HOADON.SL,CHITIET_HOADON.THANHTIEN
 FROM CHITIET_HOADON  , HOADON , BENHNHAN 
 WHERE CHITIET_HOADON.MAHD = HOADON.MAHD AND HOADON.MABN = BENHNHAN.MABN AND (BENHNHAN.TENBN LIKE N'%'+@TEN+'%' OR BENHNHAN.TENBN  = @TEN)
 GO

 CREATE PROC SP_DS_BACSI_KHOA 
 AS
 SELECT * 
 FROM NHANVIEN , KHOA 
 WHERE NHANVIEN.MAKHOA = KHOA.MAK AND NHANVIEN.MANV LIKE 'BS%'
 GO