-- CÁCH CHỨC NĂNG HỖ TRỢ CHO VIỆC TÌM KIẾM VÀ LỌC DANH SÁCH 
-- LẤY CHUỖI HỌ TÊN CỦA BỆNH NHÂN RA 

CREATE PROC SP_LAYHOTEN_BENHNHAN (@MABN CHAR (20))
AS
 SELECT CONCAT(HOBN,'',TENBN) AS N'HỌ VÀ TÊN', MABN
 FROM BENHNHAN 
 WHERE MABN = @MABN 
GO 
EXEC SP_LAYHOTEN_BENHNHAN 'BN0001'
GO 

-- LẤY CHUỖI HỌ TÊN CỦA NHÂN VIÊN RA 

CREATE PROC SP_LAYHOTEN_NHANVIEN (@MANV CHAR (20))
AS
 SELECT CONCAT(HONV,'',TENNV) AS N'HỌ VÀ TÊN' , MANV
 FROM NHANVIEN 
 WHERE MANV = @MANV 
GO 
EXEC SP_LAYHOTEN_NHANVIEN 'NV0001'
GO 

CREATE PROC SP_LAYDS_BACSI
AS
SELECT *, CONCAT(HONV,'',TENNV) AS 'HOTEN' FROM NHANVIEN WHERE MANV LIKE 'BS%'
GO

CREATE PROC SP_LAYDS_NHANVIEN
AS
SELECT *, CONCAT(HONV,'',TENNV) AS 'HOTEN'FROM NHANVIEN WHERE MANV LIKE 'NV%'
GO
-- lọc danh sách phòng đièu trị bằng mã phòng 
CREATE PROC SO_LOCDS_BANGMAPHG (@MAPDT CHAR (20))
AS
SELECT * FROM BENHNHAN_PHONGDIEUTRI WHERE PHGDT = @MAPDT 
GO 



