-- lê anh hào 

 -- TẠO STORE PROCEDURES BỆNH ÁN 
 CREATE  PROC SP_THEMBENHAN (@MABA CHAR (20)  ,@MABN CHAR (20),@NGAYNHAPVIEN DATE , @NGAYXUATVIEN DATE, @KETQUA NVARCHAR (50))
 AS 
 INSERT INTO BENHAN VALUES (@MABA,@MABN,@NGAYNHAPVIEN,@NGAYXUATVIEN, @KETQUA )
 GO 

 SELECT*FROM BENHAN 
 GO 
--EXEC SP_THEMBENHAN'BA1011','BN00010','09/12/2023',null,N'VIÊM THỰC QUẢN'
--GO
	-- XOÁ 
CREATE PROC SP_XOABENHAN (@MABA CHAR (20))
AS 
DELETE BENHAN WHERE MABA = @MABA
GO 
--EXEC SP_XOABENHAN  'BA1011'
--GO

-- SỬA 
CREATE PROC SP_SUABENHAN (@MABA CHAR (20)  ,@MABN CHAR (20),@NGAYNHAPVIEN DATE , @NGAYXUATVIEN DATE, @KETQUA NVARCHAR (50))
AS
UPDATE BENHAN 
SET MABN = @MABN ,
    NGAYNHAPVIEN = @NGAYNHAPVIEN ,
	NGAYXUATVIEN = @NGAYXUATVIEN
   ,KETQUA = @KETQUA 
WHERE MABA = @MABA 
GO 
--EXEC SP_SUABENHAN  'BA1011','BN00010',null,null,N'VIÊM THỰC QUẢN CẤP TÍNH'
--GO 

 -- TẠO STORE PROCEDURES BỆNH NHÂN  
 CREATE  PROC SP_THEMBENHNHAN (@MABN CHAR (20), @HOBN NVARCHAR(30), @TENBN NVARCHAR (30), @SODTH VARCHAR(11), 
                               @DIACHI NVARCHAR(50), @NGAYSINH DATETIME , @PHAI NVARCHAR(10), @MABHYT CHAR (15))
 AS 
 INSERT INTO BENHNHAN VALUES (@MABN, @HOBN, @TENBN, @SODTH, @DIACHI, @NGAYSINH, @PHAI, @MABHYT )
 GO 

 SELECT * FROM BENHNHAN 
 GO 

 --EXEC SP_THEMBENHNHAN 'BN00011',N'LÊ NGỌC MINH',N'ĐẮC','0813994098',N'24 KỲ ĐÔNG ,Q3,TP.HCM','06/21/2005',N'NAM',null
 --GO
	-- XOÁ 
CREATE PROC SP_XOABENHNHAN (@MABN CHAR (20))
AS 
DELETE BENHNHAN WHERE MABN = @MABN
GO 

--EXEC SP_XOABENHNHAN 'BN00011'
GO 
-- SỬA 
CREATE PROC SP_SUABENHNHAN (@MABN CHAR (20), @HOBN NVARCHAR(30), @TENBN NVARCHAR (30), @SODTH VARCHAR(11), 
                            @DIACHI NVARCHAR(50), @NGAYSINH DATETIME , @PHAI NVARCHAR(10), @MABHYT CHAR (15))
AS
UPDATE BENHNHAN
SET HOBN = @HOBN , 
    TENBN = @TENBN , 
	SODTH = @SODTH , 
	DIACHI = @DIACHI , 
	NGAYSINH = @NGAYSINH , 
	PHAI = @PHAI , 
	MABHYT = @MABHYT
WHERE MABN = @MABN 
GO 

--EXEC SP_SUABENHNHAN 'BN00011',N'LÊ MINH',N'ĐẮC','0813994099',N'24 KỲ ĐÔNG ,Q3,TP.HCM','02/21/2005',N'NAM',null
--GO
 -- TẠO STORE PROCEDURES DỊCH VỤ  
 CREATE  PROC SP_THEMDV (@MADV CHAR (20), @TENDV NVARCHAR (100), @GIA MONEY)
 AS 
 INSERT INTO DICHVU VALUES (@MADV   ,@TENDV , @GIA )
 GO 

 SELECT * FROM DICHVU 
 GO 
 --EXEC SP_THEMDV 'DV0019',N'Nội soi trực tràng ống mềm không sinh thiết','895,000'
 GO 
	-- XOÁ 
CREATE PROC SP_XOADV (@MADV CHAR (20))
AS 
DELETE DICHVU WHERE MADV = @MADV
GO 
 --EXEC SP_XOADV 'DV0019'
 GO 
-- SỬA 
CREATE PROC SP_SUADV (@MADV CHAR (20), @TENDV NVARCHAR (100), @GIA MONEY)
AS
UPDATE DICHVU 
SET TENDV = @TENDV
   ,GIA = @GIA 
WHERE MADV = @MADV
GO 
 --EXEC SP_SUADV 'DV0019',N'KHÁM TỔNG QUÁT','200,000'
 GO 

 
-- THUỴ NHIÊN 

---HOA DON
SELECT * FROM HOADON
GO
 --THEM HOA DON
CREATE PROC SP_THEMHOADON(@MAHD CHAR (20), @MABN CHAR (20), @NGAYLAP DATE, @THANHTIEN MONEY  )
AS 
INSERT INTO HOADON VALUES (@MAHD, @MABN ,@NGAYLAP,@THANHTIEN  )
GO 
--EXEC SP_THEMHOADON 'HD00023', 'BN0003'
GO

--SUA HOA DON
CREATE PROC SP_SUAHOADON (@MAHD CHAR (20), @MABN CHAR (20), @NGAYLAP DATE )
AS
UPDATE HOADON
SET
MABN =@MABN,
NGAYLAP=@NGAYLAP
WHERE MAHD=@MAHD
GO
--EXEC SP_SUAHOADON 'HD00023', 'BN00010',null 
GO
--XOA HOA DON
CREATE PROC SP_XOAHOADON (@MAHD CHAR (20) )
AS
DELETE CHITIET_HOADON WHERE MAHD = @MAHD 
DELETE HOADON
WHERE MAHD =@MAHD 
GO
--EXEC SP_XOAHOADON 'HD00023'
GO
-- CẬP NHẬP THÀNH TIỀN CHO  HOÁ ĐƠN 
CREATE PROC SP_CAPNHAP_THANHTIEN_HOADON (@MAHD CHAR(20))
AS 
UPDATE HOADON
SET THANHTIEN =  CT.TONG
FROM HOADON  
INNER JOIN (SELECT MAHD , SUM(THANHTIEN)AS TONG
FROM CHITIET_HOADON 
GROUP BY MAHD) CT ON CT.MAHD = HOADON.MAHD 
GO
-- CẬP NHẬP THÀNH TIỀN VÀ SỐ LƯỢNG CHO CHI TIẾT  HOÁ ĐƠN 
CREATE PROC SP_CAPNHAP_THANHTIEN_SL_CHITIET_HOADON_DICHVU 
AS 
UPDATE CHITIET_HOADON 
SET SL = (SDDV.SL),
THANHTIEN = (SDDV.SL*DV.GIA)
FROM CHITIET_HOADON CT 
INNER JOIN SUDUNG_DICHVU SDDV  ON SDDV.MADV = CT.MAL
INNER JOIN DICHVU  DV ON DV.MADV = SDDV.MADV 
WHERE CT.MAL LIKE 'DV%'
GO 
-- CẬP NHẬP THÀNH TIỀN VÀ SỐ LƯỢNG CHO HOÁN ĐƠN LOẠI THUỐC 
CREATE PROC SP_CAPNHAP_THANHTIEN_SL_CHITIET_HOADON_THUOC
AS 
UPDATE CHITIET_HOADON 
SET SL = (MT.SL),
THANHTIEN = (MT.SL*TH.GIA)
FROM CHITIET_HOADON CT 
INNER JOIN MUA_THUOC MT ON MT.MATHUOC= CT.MAL
INNER JOIN THUOC TH ON TH.MATHUOC = MT.MATHUOC
WHERE CT.MAL LIKE 'TH%'
GO 

-- CHI TIẾT HOÁ ĐƠN 
SELECT * FROM CHITIET_HOADON 
GO 
 -- THÊM CHI TIẾT HOÁ ĐƠN 
 CREATE PROC SP_THEM_CHITIET_HOADON(@MAHD CHAR(20), @MAL CHAR(20),@TENL NVARCHAR(100),@SL INT, @MABS CHAR(20) )
AS
BEGIN
    DECLARE @GIA MONEY;
    IF LEFT(@MAL, 2) = 'TH'
    BEGIN
  
        SELECT @GIA = GIA FROM THUOC WHERE MATHUOC = @MAL
        INSERT INTO MUA_THUOC VALUES (@MAL, (SELECT MABN FROM HOADON WHERE MAHD = @MAHD), @SL,@MABS)
    END
    ELSE 
    BEGIN
        SELECT @GIA = GIA FROM DICHVU WHERE MADV = @MAL
        INSERT INTO SUDUNG_DICHVU VALUES (@MAL, (SELECT MABN FROM HOADON WHERE MAHD = @MAHD), GETDATE(), @SL)
    END

    INSERT INTO CHITIET_HOADON (MAHD, MAL, TENL, SL, THANHTIEN)
    VALUES (@MAHD, @MAL, @TENL, @SL, @SL * @GIA)

    EXEC SP_CAPNHAP_THANHTIEN_HOADON @MAHD 
END;
GO

 -- SUA CHI TIET HOA DON 
CREATE PROCEDURE SP_SUA_CHITIET_HOADON (@MAHD CHAR(20), @MAL CHAR(20),@TENL NVARCHAR(100),@SL INT, @MABS CHAR(20) )
AS
BEGIN
    DECLARE @GIA MONEY;


    IF LEFT(@MAL, 2) = 'TH'
    BEGIN

        SELECT @GIA = GIA FROM THUOC WHERE MATHUOC = @MAL;
        UPDATE MUA_THUOC
        SET SL = @SL,
		    MABS = @MABS
        WHERE MATHUOC = @MAL AND MABN = (SELECT MABN FROM HOADON WHERE MAHD = @MAHD)
    END
    ELSE 
    BEGIN
        SELECT @GIA = GIA FROM DICHVU WHERE MADV = @MAL;
        UPDATE SUDUNG_DICHVU
        SET SL = @SL
        WHERE MADV = @MAL AND MABN = (SELECT MABN FROM HOADON WHERE MAHD = @MAHD)
    END

    UPDATE CHITIET_HOADON
    SET SL = @SL, THANHTIEN = @SL * @GIA
    WHERE MAHD = @MAHD AND MAL = @MAL

    EXEC SP_CAPNHAP_THANHTIEN_HOADON @MAHD
END
GO
-- thử nghiệm 
 SELECT * FROM CHITIET_HOADON 
 GO 
 SELECT * FROM HOADON 
 GO 
--EXEC SP_SUACHITIET_HOADON 'HD0002','DV002',N'Khám Nội','3',NULL
--GO 
 -- XOÁ CHI TIẾT HOÁ ĐƠN 
 CREATE PROCEDURE SP_XOA_CHITIET_HOADON ( @MAHD CHAR(20),@MAL CHAR(20) )
AS
BEGIN
    IF LEFT(@MAL, 2) = 'TH' 
    BEGIN
        DELETE FROM MUA_THUOC WHERE MATHUOC = @MAL AND MABN = (SELECT MABN FROM HOADON WHERE MAHD = @MAHD);
    END
    ELSE
    BEGIN
        DELETE FROM SUDUNG_DICHVU WHERE MADV = @MAL AND MABN = (SELECT MABN FROM HOADON WHERE MAHD = @MAHD);
    END

    DELETE FROM CHITIET_HOADON WHERE MAHD = @MAHD AND MAL = @MAL;

    EXEC SP_CAPNHAP_THANHTIEN_HOADON @MAHD;
END;
GO

 --EXEC SP_XOA_CHITIET_HOADON  'HD0002', 'DV001'
 GO

--THEM KHOA
SELECT*FROM KHOA
GO 
CREATE PROC SP_THEMKHOA (@MAK CHAR(20)  , @TENK NVARCHAR (30), @TRUONGKHOA CHAR(20) )
AS
INSERT INTO KHOA VALUES (@MAK , @TENK,@TRUONGKHOA)
GO
--EXEC SP_THEMKHOA 'KH0006',N'KHOA NHI',null
GO
--SUA KHOA
CREATE PROC SP_SUAKHOA (@MAK CHAR(20)  , @TENK NVARCHAR (30), @TRUONGKHOA CHAR(20) )
AS
UPDATE KHOA
SET TENK =@TENK
   ,MATRUONGKHOA= @TRUONGKHOA
WHERE MAK=@MAK
GO
--EXEC SP_SUAKHOA 'KH0006',N'KHOA THẦN KINH',null
GO
--XOA KHOA
CREATE PROC SP_XOAKHOA (@MAK CHAR(20)   )
AS
DELETE KHOA 
WHERE MAK=@MAK
GO
--EXEC SP_XOAKHOA  'KH0006'
GO


--THEM MUA THUOC 
SELECT * FROM MUA_THUOC 
GO 
CREATE PROC SP_THEMMUATHUOC (@MATHUOC CHAR(13), @MABN CHAR (20) , @SL INT,@MABS CHAR(20))
AS
INSERT INTO MUA_THUOC VALUES (@MATHUOC  ,@MABN  , @SL,@MABS)
GO
--EXEC SP_THEMMAUTHUOC 'TH0025','BN00010','14'
GO
--SUA MUA THUOC 
CREATE PROC SP_SUAMUATHUOC (@MATHUOC CHAR(13), @MABN CHAR (20) , @SL INT)
AS
UPDATE MUA_THUOC 
SET 
SL=@SL
WHERE MATHUOC = @MATHUOC AND MABN=@MABN 
GO

SELECT * FROM HOADON 
SELECT * FROM CHITIET_HOADON 
SELECT * FROM MUA_THUOC 
GO 
--EXEC SP_SUAMUATHUOC  'TH0017','BN0004','1'
GO
--XOA MUA THUOC 
CREATE PROC SP_XOAMUATHUOC (@MATHUOC CHAR(13), @MABN CHAR (20) )
AS
DELETE MUA_THUOC 
WHERE MATHUOC=@MATHUOC AND MABN=@MABN
GO
--EXEC SP_XOAMUATHUOC 'TH0022','BN0005'
GO


-- Trần đình nguyên khang 
-- Bảng THUOC
-- thêm
SELECT * FROM THUOC 
GO 
CREATE PROC SP_THEMTHUOC (@MATHUOC CHAR(13), @TENTHUOC NVARCHAR(100), @GIA MONEY)
AS
INSERT INTO THUOC VALUES (@MATHUOC, @TENTHUOC, @GIA)
GO
--EXEC SP_THEMTHUOC 'TH0027',N'Hỗn dịch uống Phosphalugel Sanofi giảm độ axit của  ','1 ','4.200'
GO

-- sửa
CREATE PROC SP_SUATHUOC (@MATHUOC CHAR(13), @TENTHUOC NVARCHAR(100), @GIA MONEY)
AS
UPDATE THUOC
SET TENTHUOC = @TENTHUOC, GIA = @GIA
WHERE MATHUOC = @MATHUOC
GO
--EXEC SP_SUATHUOC 'TH0027',N'Hỗn dịch uống','4','10.200'
GO
-- xoá
CREATE PROC SP_XOATHUOC (@MATHUOC CHAR(13))
AS
DELETE FROM THUOC
WHERE MATHUOC = @MATHUOC
GO
--EXEC SP_XOATHUOC 'TH0027'
GO
-- Bảng SUDUNG_DICHVU
SELECT * FROM SUDUNG_DICHVU 
GO 
-- THÊM 
CREATE PROC SP_THEMSUDUNG_DICHVU (@MADV CHAR(20), @MABN CHAR(20), @TGIAN DATE, @SL INT)
AS
INSERT INTO SUDUNG_DICHVU VALUES (@MADV, @MABN, @TGIAN,@SL)
GO
--EXEC SP_THEMSUDUNG_DICHVU 'DV0013','BN00010', '3/1/2023', '1'
GO
-- SỬA
CREATE PROC SP_SUASUDUNG_DICHVU (@MADV CHAR(20), @MABN CHAR(20), @TGIAN DATE, @SL INT)
AS
UPDATE SUDUNG_DICHVU
SET TGIAN = @TGIAN,
    SL =  @SL
WHERE MADV = @MADV AND MABN = @MABN
GO
--EXEC SP_SUASUDUNG_DICHVU 'DV0013','BN00010', '3/6/2023', '1'
GO
-- XOÁ
CREATE PROC SP_XOASUDUNG_DICHVU (@MADV CHAR(20), @MABN CHAR(20))
AS
DELETE FROM SUDUNG_DICHVU
WHERE MADV = @MADV AND MABN = @MABN
GO
--EXEC SP_XOASUDUNG_DICHVU 'DV0013','BN00010'
GO

-- Bảng PKHAM_BENHNHAN
SELECT * FROM BENHNHAN_PHONGKHAM
GO 
CREATE PROC SP_THEMBENHNHAN_PHONGKHAM (@MABN CHAR(20),@MAPK CHAR(20), @TGIAN DATE)
AS
INSERT INTO BENHNHAN_PHONGKHAM VALUES (@MABN,@MAPK,@TGIAN)
GO
--EXEC SP_THEMPKHAM_BENHNHAN 'PK08','BN0009','9/13/2023'
GO 

CREATE PROC SP_SUABENHNHAN_PHONGKHAM (@MABN CHAR(20),@MAPK CHAR(20), @TGIAN DATE)
AS
UPDATE BENHNHAN_PHONGKHAM
SET  NGAYKHAM= @TGIAN 
WHERE MAPK = @MAPK AND MABN = @MABN
GO
--EXEC SP_SUAPKHAM_BENHNHAN 'PK08','BN0009','9/30/2023'
GO 

CREATE PROC SP_XOABENHNHAN_PHONGKHAM (@MABN CHAR(20),@MAPK CHAR(20))
AS
DELETE FROM BENHNHAN_PHONGKHAM
WHERE MAPK = @MAPK AND MABN = @MABN
GO
--EXEC SP_XOAPKHAM_BENHNHAN 'PK08','BN0009'
GO 

-- bảng bệnh nhân phòng khám 
-- thêm 
CREATE PROC SP_THEMBENHNHAN_PHONGDIEUTRI (@MABN CHAR(20), @PHGDT CHAR(20), @NGAYNHAPVIEN DATE )
AS 
INSERT INTO BENHNHAN_PHONGDIEUTRI VALUES (@MABN , @PHGDT , @NGAYNHAPVIEN  ,NULL )
GO 
-- SỬA 
CREATE PROC SP_SUABENHNHAN_PHONGDIEUTRI (@MABN CHAR(20), @PHGDT CHAR(20), @NGAYNHAPVIEN DATE , @NGAYXUATVIEN DATE)
AS 
UPDATE BENHNHAN_PHONGDIEUTRI
SET NGAYNHAPVIEN = @NGAYNHAPVIEN , 
NGAYXUATVIEN = @NGAYXUATVIEN 
WHERE MABN = @MABN AND  PHGDT = @PHGDT 
GO 
-- XOÁ
CREATE PROC SP_XOABENHNHAN_PHONGDIEUTRI (@MABN CHAR(20), @PHGDT CHAR(20))
AS 
DELETE BENHNHAN_PHONGDIEUTRI WHERE MABN = @MABN AND  PHGDT = @PHGDT 
GO 
-- Bảng PHONGKHAM
SELECT * FROM PHONGKHAM 
GO 
CREATE PROC SP_THEMPHONGKHAM (@MAPK CHAR(20), @MAK CHAR(20),@MABS CHAR (20),@LOAIPK NVARCHAR (100))
AS
INSERT INTO PHONGKHAM VALUES (@MAPK, @MAK,@MABS,@LOAIPK)
GO

CREATE PROC SP_SUAPHONGKHAM (@MAPK CHAR(20), @MAK CHAR(20),@MABS CHAR (20),@LOAIPK NVARCHAR (100))
AS
UPDATE PHONGKHAM
SET MAK = @MAK,
  MABS = @MABS , 
  LOAIPK = @LOAIPK
WHERE MAPK = @MAPK
GO

CREATE PROC SP_XOAPHONGKHAM (@MAPK CHAR(20))
AS
DELETE FROM PHONGKHAM
WHERE MAPK = @MAPK 
GO


-- Bảng PHONGDIEUTRI

CREATE PROC SP_THEMPHONGDIEUTRI (@MAPDT CHAR(20), @LOAIPHONG NVARCHAR(30),@MABS CHAR(20), @MAKHOA CHAR(20))
AS
INSERT INTO PHONGDIEUTRI VALUES (@MAPDT, @LOAIPHONG,@MABS,@MAKHOA)
GO

CREATE PROC SP_SUAPHONGDIEUTRI (@MAPDT CHAR(20), @LOAIPHONG NVARCHAR(30),@MABS CHAR(20), @MAKHOA CHAR(20))
AS
UPDATE PHONGDIEUTRI
SET LOAIPHONG = @LOAIPHONG,
    MABS = @MABS,
    MAKHOA = @MAKHOA
WHERE MAPDT = @MAPDT
GO

CREATE PROC SP_XOAPHONGDIEUTRI (@MAPDT CHAR(20))
AS
DELETE FROM PHONGDIEUTRI
WHERE MAPDT = @MAPDT
GO


-- Bảng NHANVIEN

CREATE PROC SP_THEMNHANVIEN (@MANV CHAR(20), @HONV NVARCHAR(30), @TENNV NVARCHAR(30), @DIACHI NVARCHAR(50), @NGAYSINH DATETIME, @PHAI NVARCHAR(10), @CHUCVU NVARCHAR(20),@VAITRO NVARCHAR(255), @NGAYLV DATETIME, @MAKHOA CHAR(20))
AS
INSERT INTO NHANVIEN VALUES (@MANV, @HONV, @TENNV, @DIACHI, @NGAYSINH, @PHAI, @CHUCVU,@VAITRO, @NGAYLV,@MAKHOA)
GO

CREATE PROC SP_SUANHANVIEN (@MANV CHAR(20), @HONV NVARCHAR(30), @TENNV NVARCHAR(30), @SODTH VARCHAR(11), @DIACHI NVARCHAR(50), @NGAYSINH DATETIME, @PHAI NVARCHAR(10), @CHUCVU NVARCHAR(20),@VAITRO NVARCHAR(255),@NGAYLV DATETIME, @MAKHOA CHAR(20))
AS
UPDATE NHANVIEN
SET HONV = @HONV, TENNV = @TENNV, DIACHI = @DIACHI, NGAYSINH = @NGAYSINH, PHAI = @PHAI, CHUCVU = @CHUCVU,VAITRO = @VAITRO, NGAYLV = @NGAYLV, MAKHOA = @MAKHOA
WHERE MANV = @MANV
GO

CREATE PROC SP_XOANHANVIEN (@MANV CHAR(20))
AS
DELETE FROM NHANVIEN
WHERE MANV = @MANV
GO
