--------UPDATE TRƯỞNG KHOA CHO KHOA-------------------
UPDATE KHOA 
SET MATRUONGKHOA = 'BS00014'
WHERE MAK = 'KH0001'
GO 
UPDATE KHOA 
SET MATRUONGKHOA = 'BS00011'
WHERE MAK = 'KH0002'
GO 
UPDATE KHOA 
SET MATRUONGKHOA = 'BS00019'
WHERE MAK = 'KH0003'
GO 
UPDATE KHOA 
SET MATRUONGKHOA = 'BS00020'
WHERE MAK = 'KH0004'
GO 
UPDATE KHOA 
SET MATRUONGKHOA = 'BS00018'
WHERE MAK = 'KH0005'
GO 

SELECT* FROM KHOA 
GO 

-- UPDATE CHI TIẾT HOÁ ĐƠN 
UPDATE CHITIET_HOADON
SET SL = SDV.SL,
    THANHTIEN = SDV.SL * DV.GIA
FROM CHITIET_HOADON CT
INNER JOIN SUDUNG_DICHVU SDV ON CT.MAL = SDV.MADV
INNER JOIN DICHVU DV ON SDV.MADV = DV.MADV
WHERE CT.MAL LIKE 'DV%'
GO
SELECT * FROM CHITIET_HOADON 
GO 

UPDATE CHITIET_HOADON
SET SL = MT.SL,
    THANHTIEN = MT.SL * T.GIA
FROM CHITIET_HOADON CT
INNER JOIN MUA_THUOC MT ON CT.MAL = MT.MATHUOC
INNER JOIN THUOC T ON MT.MATHUOC = T.MATHUOC
WHERE CT.MAL LIKE 'TH%'
GO 
---- XOÁ 
--DELETE FROM CHITIET_HOADON WHERE maHD = 'HD0001' AND MAL ='TH0020'; 
--UPDATE HOADON
--SET THANHTIEN = (
--    SELECT SUM(thanhTien)
--    FROM CHITIET_HOADON
--    WHERE maHD = 'HD0001'
--)
--WHERE MAHD = 'HD0001'
--GO 
---- update HOÁ ĐƠN 
--UPDATE ChiTietHoaDon
SELECT * FROM HOADON 
GO 

UPDATE HOADON
SET THANHTIEN =  CT.TONG
FROM HOADON  
INNER JOIN (SELECT MAHD , SUM(THANHTIEN)AS TONG
FROM CHITIET_HOADON 
GROUP BY MAHD) CT ON CT.MAHD = HOADON.MAHD 
GO


